package com.example.gameworkbench.common.enums;

public enum ArtifactType {
    REQUIREMENT_BREAKDOWN_RESULT,
    API_DESIGN_RESULT,
    BUG_ANALYSIS_RESULT,
    PROMPT_GENERATE_RESULT,
    GAME_CONCEPT_RESULT,
    CORE_LOOP_DESIGN_RESULT,
    TASK_BREAKDOWN_RESULT,
    GAME_CONFIG,
    RESOURCE_MANIFEST,
    BALANCE_SUGGESTION
}
