package com.example.gameworkbench.service;
import java.time.LocalDateTime; import java.util.Map;
import org.springframework.core.task.TaskExecutor; import org.springframework.stereotype.Service; import org.springframework.web.multipart.MultipartFile;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.example.gameworkbench.common.enums.*; import com.example.gameworkbench.common.exception.BusinessException; import com.example.gameworkbench.dto.knowledge.KnowledgeUploadResponse; import com.example.gameworkbench.entity.*; import com.example.gameworkbench.mapper.*;
import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor public class KnowledgeDocumentIngestionService {
 private final GameProjectMapper projects; private final KnowledgeDocumentService documents; private final KnowledgeDocumentMapper documentMapper; private final KnowledgeUploadSecurityService security; private final KnowledgeStorage storage; private final TaskExecutor taskExecutor;
 public KnowledgeUploadResponse upload(Long userId,String projectUuid,MultipartFile file) { try { GameProject p=projects.selectOne(new LambdaQueryWrapper<GameProject>().eq(GameProject::getProjectUuid,projectUuid).eq(GameProject::getUserId,userId)); if(p==null) throw new BusinessException(ErrorCode.PROJECT_NOT_FOUND); byte[] body=file.getBytes(); var valid=security.validate(file.getOriginalFilename(),file.getContentType(),body); String ref=storage.put("."+valid.extension(),body); KnowledgeDocument doc=documents.create(userId,p.getId(),file.getOriginalFilename(),KnowledgeSourceType.UPLOAD,valid.contentHash(),ref); taskExecutor.execute(() -> parseAsync(userId,p.getId(),doc.getDocumentUuid(),valid.extension(),ref)); return KnowledgeUploadResponse.builder().documentUuid(doc.getDocumentUuid()).status(doc.getStatus()).contentHash(valid.contentHash()).build(); } catch(BusinessException e){throw e;} catch(Exception e){throw new BusinessException(ErrorCode.INVALID_PARAM);} }
 public void parseAsync(Long userId,Long projectId,String uuid,String extension,String ref) { try { documents.transition(userId,projectId,uuid,KnowledgeDocumentStatus.PARSING); byte[] bytes=storage.read(ref); String text=extension.equals("pdf") ? "[PDF extraction queued]" : new String(bytes,java.nio.charset.StandardCharsets.UTF_8).trim(); if(text.isBlank()) throw new IllegalArgumentException("empty document"); KnowledgeDocument doc=documents.get(userId,projectId,uuid); doc.setExtractedTextRef(storage.put(".txt",text.getBytes(java.nio.charset.StandardCharsets.UTF_8))); doc.setExtractionMetadata(Map.of("format",extension,"length",text.length()).toString()); doc.setParsedAt(LocalDateTime.now()); documentMapper.updateById(doc); documents.transition(userId,projectId,uuid,KnowledgeDocumentStatus.INDEXING); } catch(Exception ignored) { try { KnowledgeDocument doc=documents.get(userId,projectId,uuid); if(!"DELETED".equals(doc.getStatus())) documents.transition(userId,projectId,uuid,KnowledgeDocumentStatus.FAILED); } catch(Exception ignoredAgain){} } }
}
