create table director_run (
    id bigint primary key auto_increment,
    run_uuid varchar(36) not null,
    user_id bigint not null,
    project_id bigint not null,
    idempotency_key varchar(128) not null,
    request_fingerprint char(64) not null,
    goal_json text not null,
    goal_digest char(64) not null,
    budget_json text not null,
    status varchar(24) not null,
    state_version bigint not null default 0,
    checkpoint_json text not null,
    waiting_approval_ref varchar(255) null,
    error_code varchar(80) null,
    created_at datetime(6) not null,
    updated_at datetime(6) not null,
    completed_at datetime(6) null,
    constraint uk_director_run_uuid unique (run_uuid),
    constraint uk_director_run_idempotency unique (user_id, project_id, idempotency_key),
    constraint fk_director_run_project foreign key (project_id) references game_project(id),
    constraint chk_director_run_status check (status in ('PENDING','RUNNING','WAITING_EXPERIMENT','WAITING_APPROVAL','SUCCEEDED','FAILED','CANCELED'))
);
create index idx_director_run_project_created on director_run(project_id, created_at);

create table director_decision (
    id bigint primary key auto_increment,
    decision_uuid varchar(36) not null,
    director_run_id bigint not null,
    project_id bigint not null,
    round_number int not null,
    state_version bigint not null,
    kind varchar(24) not null,
    reason_summary varchar(500) not null,
    decision_digest char(64) not null,
    model_evidence_json text not null,
    payload_json text not null,
    created_at datetime(6) not null,
    constraint uk_director_decision_uuid unique (decision_uuid),
    constraint uk_director_decision_round unique (director_run_id, round_number),
    constraint fk_director_decision_run foreign key (director_run_id) references director_run(id),
    constraint fk_director_decision_project foreign key (project_id) references game_project(id),
    constraint chk_director_decision_kind check (kind in ('CALL_TOOL','REQUEST_APPROVAL','FINISH','FAIL'))
);

create table director_tool_call (
    id bigint primary key auto_increment,
    call_uuid varchar(80) not null,
    director_run_id bigint not null,
    decision_id bigint not null,
    project_id bigint not null,
    tool_name varchar(80) not null,
    tool_version varchar(20) not null,
    idempotency_key varchar(128) not null,
    status varchar(24) not null,
    input_digest char(64) not null,
    input_summary varchar(1000) not null,
    output_digest char(64) null,
    output_summary varchar(2000) null,
    result_ref varchar(255) null,
    duration_ms bigint null,
    error_code varchar(80) null,
    retry_count int not null default 0,
    created_at datetime(6) not null,
    completed_at datetime(6) null,
    constraint uk_director_tool_call_uuid unique (call_uuid),
    constraint uk_director_tool_idempotency unique (director_run_id, idempotency_key),
    constraint fk_director_tool_run foreign key (director_run_id) references director_run(id),
    constraint fk_director_tool_decision foreign key (decision_id) references director_decision(id),
    constraint fk_director_tool_project foreign key (project_id) references game_project(id)
);

create table experiment_candidate (
    id bigint primary key auto_increment,
    candidate_uuid varchar(36) not null,
    director_run_id bigint not null,
    project_id bigint not null,
    ordinal_number int not null,
    status varchar(24) not null,
    prototype_version_uuid varchar(36) null,
    player_run_uuid varchar(36) null,
    machine_episode_uuid varchar(36) null,
    config_digest char(64) null,
    evidence_json text not null,
    created_at datetime(6) not null,
    updated_at datetime(6) not null,
    constraint uk_experiment_candidate_uuid unique (candidate_uuid),
    constraint uk_experiment_candidate_ordinal unique (director_run_id, ordinal_number),
    constraint fk_experiment_candidate_run foreign key (director_run_id) references director_run(id),
    constraint fk_experiment_candidate_project foreign key (project_id) references game_project(id),
    constraint fk_experiment_candidate_version foreign key (prototype_version_uuid) references prototype_version(version_uuid),
    constraint fk_experiment_candidate_player_run foreign key (player_run_uuid) references player_run(run_uuid),
    constraint fk_experiment_candidate_episode foreign key (machine_episode_uuid) references machine_episode(episode_uuid)
);
create index idx_experiment_candidate_run on experiment_candidate(director_run_id, ordinal_number);
