export const appRoutes = [
  { path: "/login", name: "auth", component: () => import("../features/auth/AuthPage.vue"), meta: { public: true } },
  { path: "/forbidden", name: "forbidden", component: () => import("../shared/ui/ForbiddenPage.vue"), meta: { title: "权限不足" } },
  { path: "/projects", name: "projects", component: () => import("../features/projects/ProjectsPage.vue"), meta: { capability: "projects.read" } },
  { path: "/projects/:projectUuid/studio", name: "studio", component: () => import("../features/generation/GenerationStudioPage.vue"), meta: { title: "Cocos 生成台", capability: "generation.read" } },
  { path: "/projects/:projectUuid/artifacts", name: "artifacts", component: () => import("../features/artifacts/ArtifactOverviewPage.vue"), meta: { title: "Artifact 总览", capability: "artifacts.read" } },
  { path: "/projects/:projectUuid/artifacts/:artifactUuid", name: "artifact-detail", component: () => import("../features/artifacts/ArtifactDetailPage.vue"), meta: { title: "Artifact 详情", capability: "artifacts.read" } },
  { path: "/projects/:projectUuid/player-runs", name: "player-runs", component: () => import("../features/shared/FeaturePlaceholderPage.vue"), meta: { title: "Player Runs", capability: "player-runs.read" } },
  { path: "/projects/:projectUuid/knowledge", name: "knowledge", component: () => import("../features/knowledge/KnowledgeLibraryPage.vue"), meta: { title: "项目知识库", capability: "knowledge.read" } },
  { path: "/projects/:projectUuid/workflow-runs", name: "workflow-runs", component: () => import("../features/shared/FeaturePlaceholderPage.vue"), meta: { title: "Workflow Runs", capability: "workflow-runs.manage" } },
  { path: "/projects/:projectUuid/idea-studio", name: "idea-studio", component: () => import("../features/studio/StudioPage.vue"), meta: { title: "旧版创作台", capability: "workflow-runs.manage" } },
  { path: "/projects/:projectUuid/versions", name: "versions", component: () => import("../features/prototypes/PrototypeVersionsPage.vue"), meta: { title: "原型版本", capability: "prototype-versions.read" } },
  { path: "/projects/:projectUuid/versions/:versionUuid/episodes", name: "episodes", component: () => import("../features/episodes/EpisodeTracePage.vue"), meta: { title: "Episode 详情", capability: "machine-episodes.read" } },
  { path: "/projects/:projectUuid/director", name: "director-create", component: () => import("../features/director/DirectorRunPage.vue"), meta: { title: "Director Run", capability: "director-runs.manage" } },
  { path: "/projects/:projectUuid/director-runs/:runUuid", name: "director-run", component: () => import("../features/director/DirectorRunPage.vue"), meta: { title: "Director Run", capability: "director-runs.manage" } },
  { path: "/runs/:workflowRunUuid", name: "run", component: () => import("../features/runs/RunPage.vue"), meta: { title: "Workflow Run", capability: "workflow-runs.manage" } },
  { path: "/admin/dashboard", name: "admin-dashboard", component: () => import("../features/admin/AdminDashboardPage.vue"), meta: { title: "运营总览", capability: "admin.dashboard" } },
  { path: "/admin/agent-runs", name: "admin-agent-runs", component: () => import("../features/admin/AdminAgentRunsPage.vue"), meta: { title: "Agent Runs", capability: "admin.agent-runs" } },
  { path: "/admin/prompt-ops", name: "admin-prompt-ops", component: () => import("../features/prompt-ops/PromptOpsPage.vue"), meta: { title: "Prompt 运维", capability: "prompt-ops.manage" } },
  { path: "/admin/analytics", name: "admin-analytics", component: () => import("../features/prompt-analytics/PromptAnalyticsPage.vue"), meta: { title: "Prompt 指标", capability: "prompt-analytics.read" } },
  { path: "/admin/diagnostics", name: "admin-diagnostics", component: () => import("../features/admin/AdminDiagnosticsPage.vue"), meta: { title: "系统诊断", capability: "admin.diagnostics" } },
  { path: "/demo/play", name: "demo", component: () => import("../features/demo/DemoPage.vue"), meta: { title: "非生产 Demo", capability: "admin.diagnostics", nonProdOnly: true } },
  { path: "/:pathMatch(.*)*", redirect: "/projects" }
];
